# Funding platforms for Pickle Play
# Uncomment and configure the platforms you want to use

# github: [username]
# patreon: username
# open_collective: pickle-play
# ko_fi: pickle-play
# tidelift: npm/pickle-play
# custom: ['https://www.buymeacoffee.com/pickle-play']
